In [16]:
import open3d as o3d
import numpy as np

In [11]:
mesh = o3d.io.read_triangle_mesh("1.stl")
    

In [25]:
print("Try to render a mesh with normals (exist: " +
      str(mesh.has_vertex_normals()) + ") and colors (exist: " +
      str(mesh.has_vertex_colors()) + ")")
o3d.visualization.draw_geometries([mesh])
print("A mesh with no normals and no colors does not look good.")

Try to render a mesh with normals (exist: True) and colors (exist: True)
A mesh with no normals and no colors does not look good.


In [27]:
print("Computing normal and rendering it.")
mesh_with_norm = mesh
mesh_with_norm.compute_vertex_normals()
print(np.asarray(mesh_with_norm.triangle_normals))
o3d.visualization.draw_geometries([mesh_with_norm])

Computing normal and rendering it.
[[-0.03459856  0.01525301  0.99928489]
 [-0.0365264  -0.01114121  0.99927058]
 [-0.03942616  0.02542192  0.99889905]
 ...
 [-0.12968352  0.0292927   0.99112266]
 [-0.12127604  0.02154669  0.99238494]
 [-0.12127555  0.0215437   0.99238506]]


In [14]:
print("Painting the mesh")
mesh1 = mesh_with_norm
mesh1.paint_uniform_color([1, 0.706, 0])
o3d.visualization.draw_geometries([mesh1])

Painting the mesh


In [32]:
import pyvista as pv


mesh_pv = pv.read("1.stl")
# cpos = mesh_pv.plot(show_edges=False, cmap='jet')

In [36]:
pcd = o3d.io.read_point_cloud("1234combined_2.xyz", format='xyz')

In [38]:
o3d.visualization.draw_geometries([pcd])